### ISSUE TITLE
[BUG] Prisma 6.2.0 generating extra invalid updateMany schemas

### ISSUE THREAD

**Issue by willscottrod** [chrishoermann/zod-prisma-types#306]
**Describe the bug**
When using prisma 6.2.0, extra invalid schemas all starting with 'updateMany' are being generated. This doesn't seem to affect any other parts of the generation other than creating extra output type schemas. 

I am assuming this is related to Prisma's new batch function: updateManyAndReturn
https://github.com/prisma/prisma/releases/tag/6.2.0

**Screenshots**

![image](https://github.com/user-attachments/assets/0c31ae08-2c33-4d35-a0c0-f2f20afb52e3)

Code below

```
import { z } from 'zod';
import type { Prisma } from '@prisma/client';
import { AccountUpdateManyMutationInputSchema } from '../inputTypeSchemas/AccountUpdateManyMutationInputSchema'
import { AccountUncheckedUpdateManyInputSchema } from '../inputTypeSchemas/AccountUncheckedUpdateManyInputSchema'
import { AccountWhereInputSchema } from '../inputTypeSchemas/AccountWhereInputSchema'

export const updateManyAccountCreateManyAndReturnArgsSchema: z.ZodType<Prisma.updateManyAccountCreateManyAndReturnArgs> = z.object({
  data: z.union([ AccountUpdateManyMutationInputSchema,AccountUncheckedUpdateManyInputSchema ]),
  where: AccountWhereInputSchema.optional(),
}).strict() ;

export default updateManyAccountCreateManyAndReturnArgsSchema;

```

**Package versions (please complete the following information):**
 - zod:  "^3.24.1"
 - prisma:"^6.2.0"

**Additional context**
This problem was fixed by downgrading to Prisma 6.1.0. This only occurs in Prisma 6.2.0

**Comment by hayedewit** [comment]
Can confirm. The wrong type is being used.

Used type: `updateManyAccountCreateManyAndReturnArgs`

Correct type: `AccountUpdateManyAndReturnArgs`

**Comment by PS1TD** [comment]
Can confirm, having the same issue with the same zod & prisma versions.

**Comment by aurelien-cuvelier** [comment]
I also confirm, i have the same issue:

"zod-prisma-types": "^3.2.1"
"prisma": "^6.2.1"

**Comment by JackMBurch** [comment]
# Temporary fix until the package is fixed:

Add this to your package.json

```json
  "scripts": {
    "generate": "npx prisma generate && npm run postprocess",
    "postprocess-temp": "sed -i -re 's/Prisma.updateMany([a-Z]+)CreateManyAndReturnArgs/Prisma.\\1UpdateManyAndReturnArgs/g' ./prisma/zod/index.ts && echo 'Prisma postprocess complete \u001b[92m✔\u001b[0m' # This is a temporary fix to https://github.com/chrishoermann/zod-prisma-types/issues/306",
  }
```
Now run `npm run generate` instead of `npx prisma generate` and the zod file should be correct.

### Mac
If you are on mac you will have to add a pair of single quotes `''` after the `sed -i`

### pnpm
If using pnpm change `npx` to `pnpm exec` and `npm run` to `pnpm`

**Comment by 6farer** [comment]
If there's no merge, here's an OS agnostic fix based on @JackMBurch so you can run in your CI

`scripts/prisma-postprocess.js`
```scripts/prisma-postprocess.js
import { readFileSync, writeFileSync } from "node:fs";

const GENERATED_FILE_PATH = "./generated/WHEREVER_YOUR_ZOD_OUTPUT_IS";

// This is a temporary fix to https://github.com/chrishoermann/zod-prisma-types/issues/306
function fixPrismaTypes() {
  try {
    const content = readFileSync(GENERATED_FILE_PATH, "utf8");
    const updatedContent = content.replace(
      /Prisma\.updateMany([a-zA-Z]+)CreateManyAndReturnArgs/g,
      "Prisma.$1UpdateManyAndReturnArgs",
    );
    writeFileSync(GENERATED_FILE_PATH, updatedContent);
    console.log("\u001b[92m✔\u001b[0m Prisma postprocess complete");
  } catch (error) {
    console.error("\u001b[91m✘\u001b[0m Prisma postprocess failed:", error);
    process.exit(1);
  }
}

fixPrismaTypes();
```

`package.json`
```package.json
"scripts": {
    "generate": "pnpm exec prisma generate && pnpm prisma:postprocess",
    "prisma:postprocess": "node scripts/prisma-postprocess.js",
```

**Comment by Lolymoly** [comment]
Here is the modify version from @6farer to automatically applies a fix to all affected .ts files in the zod output folder
(Changing `updateManyXCreateManyAndReturnArgs` to `XUpdateManyAndReturnArgs`



```javascript
// Source: https://github.com/chrishoermann/zod-prisma-types/issues/306#issuecomment-2623589838
// This is temporary code to fix the zod-prisma issue

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Replace GENERATED_FOLDER_PATH value with your path to zod outputTypeSchemas folder
const __dirname = dirname(fileURLToPath(import.meta.url));
const GENERATED_FOLDER_PATH = join(__dirname, "../zod/outputTypeSchemas");

// Check if the folder exists before proceeding
if (!existsSync(GENERATED_FOLDER_PATH)) {
  console.error("\u001b[91m✘\u001b[0m Error: Zod output folder not found:", GENERATED_FOLDER_PATH);
  process.exit(1);
}

let modifiedFiles = 0; // Counter for affected files

// Apply fix to all .ts files inside `outputTypeSchemas`
readdirSync(GENERATED_FOLDER_PATH).forEach((file) => {
  if (file.endsWith(".ts")) {
	const filePath = join(GENERATED_FOLDER_PATH, file);
	const content = readFileSync(filePath, "utf8");

	// Fix incorrect Prisma type references
	const updatedContent = content.replace(
	  /Prisma\.updateMany([a-zA-Z]+)CreateManyAndReturnArgs/g,
	  "Prisma.$1UpdateManyAndReturnArgs"
	);

	// Only write and log if changes were actually made
	if (content !== updatedContent) {
	  writeFileSync(filePath, updatedContent);
	  console.log(`\u001b[92m✔\u001b[0m Fixed: ${file}`);
	  modifiedFiles++;
	}
  }
});

// Final log
if (modifiedFiles > 0) {
  console.log(`\u001b[92m✔\u001b[0m Prisma postprocess complete. Fixed ${modifiedFiles} file(s).`);
} else {
  console.log("\u001b[93m⚠\u001b[0m No files needed fixing.");
}

```

**Comment by dedupely** [comment]
@Lolymoly your code got me 90% of the way. However I had to add the `generatorHandler` to get it to run after the Zod generator had run. I suppose this is the widely accepted way to do it. Works great!

Hope this helps :)

Change `src/lib/prisma-zod-types` with your path.

```
// Source: https://github.com/chrishoermann/zod-prisma-types/issues/306#issuecomment-2623589838
// This is temporary code to fix the zod-prisma issue

import pkg from '@prisma/generator-helper';
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const { generatorHandler } = pkg;

generatorHandler({
  onManifest() {
    return {
      defaultOutput: './',
      prettyName: 'Update Prisma Zod Types Type Fix (https://github.com/chrishoermann/zod-prisma-types/issues/306#issuecomment-2623589838)',
    };
  },
  async onGenerate(options) {
    const paths = [
      resolve('./src/lib/prisma-zod-types/outputTypeSchemas'),
      resolve('./src/lib/prisma-zod-types/inputTypeSchemas'),
      resolve('./src/lib/prisma-zod-types/modelSchema')
    ];

    let modifiedFiles = 0; // Counter for affected files

    for(const path of paths) {
      // Apply fix to all .ts files inside `outputTypeSchemas`
      console.log(path);

      readdirSync(path).forEach((file) => {
        if (file.endsWith(".ts")) {
          const filePath = join(path, file);
          const content = readFileSync(filePath, "utf8");

          // Fix incorrect Prisma type references
          const updatedContent = content.replace(
            /Prisma\.updateMany([a-zA-Z]+)CreateManyAndReturnArgs/g,
            "Prisma.$1UpdateManyAndReturnArgs"
          );

          // Only write and log if changes were actually made
          if (content !== updatedContent) {
            writeFileSync(filePath, updatedContent);
            
            console.log(`\u001b[92m✔\u001b[0m Fixed: ${file}`);
            modifiedFiles++;
          }
        }
      });
    }

    // Final log
    if (modifiedFiles > 0) {
      console.log(`\u001b[92m✔\u001b[0m Prisma postprocess complete. Fixed ${modifiedFiles} file(s).`);
    } else {
      console.log("\u001b[93m⚠\u001b[0m No files needed fixing.");
    }
  }
});
```

**Comment by JackMBurch** [comment]
Awesome stuff guys, love to see the progression of a simple sed command to a fully fledged patch! 👏 

@dedupely You might want to [add syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) to that code block for readability.

**Comment by chrishoermann** [comment]
Took me a while, so thanks for the awesome fixes you build in the meantime and thanks to @willscottrod for the PR.  `updateManyAndReturn` should now be handled properly by the latest version of the genreator. Please confirm on your end if the problem is gone. Thanks!

**Comment by dedupely** [comment]
> Awesome stuff guys, love to see the progression of a simple sed command to a fully fledged patch! 👏
> 
> [@dedupely](https://github.com/dedupely) You might want to [add syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) to that code block for readability.

Done. ;)

**Comment by Sliov** [comment]
Am I the only one to still face the issue?

![Image](https://github.com/user-attachments/assets/4cf0d014-642b-41f1-b82c-70de9bc13570)

Using prisma 6.3.1 & zod-prisma-types 3.2.3

**Comment by oldo** [comment]
> Am I the only one to still face the issue?
> 
> ![Image](https://github.com/user-attachments/assets/4cf0d014-642b-41f1-b82c-70de9bc13570)
> 
> Using prisma 6.3.1 & zod-prisma-types 3.2.3

I too am facing this issue, although it's different to what the PR addressed. My issue is as you indicated that schemas are being imported multiple times.
